# Generated by Django 5.2.7 on 2025-10-10 06:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surgery_date", models.DateField(verbose_name="수술 날짜")),
                (
                    "professor_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="담당 교수"
                    ),
                ),
                (
                    "surgery_name",
                    models.CharField(blank=True, max_length=200, verbose_name="수술명"),
                ),
                (
                    "surgery_type",
                    models.CharField(
                        default="Upper", max_length=20, verbose_name="수술 타입"
                    ),
                ),
                (
                    "anesthesia",
                    models.CharField(blank=True, max_length=100, verbose_name="마취"),
                ),
                (
                    "op_side",
                    models.CharField(blank=True, max_length=50, verbose_name="Rt/Lt"),
                ),
                (
                    "op_site",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="수술 부위"
                    ),
                ),
                (
                    "surgery_room_w",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="수술방(W)"
                    ),
                ),
                (
                    "surgery_room_r",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="수술방(R)"
                    ),
                ),
                (
                    "clothing",
                    models.CharField(blank=True, max_length=100, verbose_name="환의"),
                ),
                (
                    "brace",
                    models.CharField(blank=True, max_length=100, verbose_name="보조기"),
                ),
                (
                    "op_marking",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="OP Marking"
                    ),
                ),
                (
                    "shaving_status",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Shaving"
                    ),
                ),
                (
                    "npo_status",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="자정 NPO"
                    ),
                ),
                (
                    "ast_result",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="AST 결과"
                    ),
                ),
                (
                    "ast_site",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="AST 위치"
                    ),
                ),
                (
                    "foleys_cath",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Foley's cath."
                    ),
                ),
                (
                    "iv_line",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="I.V Line"
                    ),
                ),
                (
                    "supplies",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="기타 준비물"
                    ),
                ),
                (
                    "supplies2",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="기타 준비물 2"
                    ),
                ),
                (
                    "antibiotics",
                    models.CharField(blank=True, max_length=100, verbose_name="Anti"),
                ),
                (
                    "id_bracelet",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="인식 팔찌"
                    ),
                ),
                ("memo", models.TextField(blank=True, verbose_name="메모")),
                (
                    "pre_ru_status",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Pre RU 여부"
                    ),
                ),
                (
                    "pre_ru_result",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Pre RU 결과"
                    ),
                ),
                (
                    "enema_status",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Enema 시행"
                    ),
                ),
                (
                    "enema_details",
                    models.TextField(blank=True, verbose_name="Enema 상세"),
                ),
                (
                    "spine_region",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="척추 부위"
                    ),
                ),
                (
                    "approach",
                    models.CharField(blank=True, max_length=100, verbose_name="접근법"),
                ),
                (
                    "level_count",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Level 수"
                    ),
                ),
                (
                    "hair",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="머리 처리"
                    ),
                ),
                (
                    "nipple",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nipple 처리"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="생성일시"
                    ),
                ),
            ],
            options={
                "ordering": ["-surgery_date", "-id"],
            },
        ),
    ]
