# Generated by Django 5.2.7 on 2025-10-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Precaution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "surgery_type",
                    models.CharField(
                        choices=[("Upper", "Upper"), ("T&L", "T&L"), ("Foot", "Foot")],
                        max_length=10,
                        unique=True,
                        verbose_name="수술 타입",
                    ),
                ),
                ("content", models.TextField(verbose_name="주의사항 내용")),
            ],
        ),
    ]
