# Generated by Django 5.2.7 on 2025-10-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_precaution"),
    ]

    operations = [
        migrations.CreateModel(
            name="StyleSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Active Theme",
                        editable=False,
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "active_theme",
                    models.CharField(
                        choices=[("default", "기본 테마"), ("compact", "컴팩트 테마")],
                        default="default",
                        max_length=20,
                        verbose_name="활성 테마",
                    ),
                ),
            ],
            options={
                "verbose_name": "스타일 설정",
                "verbose_name_plural": "스타일 설정",
            },
        ),
    ]
