# Generated by Django 5.2.7 on 2025-10-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_stylesetting"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stylesetting",
            options={
                "verbose_name": "메인 화면 스타일 설정",
                "verbose_name_plural": "메인 화면 스타일 설정",
            },
        ),
        migrations.RemoveField(
            model_name="stylesetting",
            name="active_theme",
        ),
        migrations.AddField(
            model_name="stylesetting",
            name="container_max_width",
            field=models.IntegerField(
                default=960,
                help_text="폼 영역의 최대 가로 크기를 픽셀(px) 단위로 입력하세요. (예: 960)",
                verbose_name="폼 컨테이너 최대 너비 (px)",
            ),
        ),
        migrations.AddField(
            model_name="stylesetting",
            name="input_font_size",
            field=models.FloatField(
                default=0.85,
                help_text="글자를 입력하는 모든 칸의 글자 크기입니다. (예: 0.85)",
                verbose_name="입력칸 글자 크기 (rem)",
            ),
        ),
        migrations.AddField(
            model_name="stylesetting",
            name="input_vertical_padding",
            field=models.FloatField(
                default=0.25,
                help_text="입력칸의 높이를 조절합니다. 숫자가 클수록 높아집니다. (예: 0.25)",
                verbose_name="입력칸 내부 세로 여백 (rem)",
            ),
        ),
        migrations.AddField(
            model_name="stylesetting",
            name="label_font_size",
            field=models.FloatField(
                default=0.85,
                help_text="'수술 날짜:', '담당 교수:' 같은 이름표의 글자 크기입니다. (예: 0.85)",
                verbose_name="라벨 글자 크기 (rem)",
            ),
        ),
        migrations.AlterField(
            model_name="stylesetting",
            name="name",
            field=models.CharField(
                default="Active Style", editable=False, max_length=50, unique=True
            ),
        ),
    ]
