# Generated by Django 5.2.7 on 2025-10-26 15:46

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_alter_stylesetting_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_type",
                    models.CharField(
                        choices=[("upper", "Upper"), ("tl", "T&L"), ("foot", "Foot")],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                "verbose_name": "주의사항",
                "verbose_name_plural": "주의사항",
            },
        ),
        migrations.DeleteModel(
            name="Precaution",
        ),
        migrations.DeleteModel(
            name="StyleSetting",
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "ordering": ["-surgery_date", "-id"],
                "verbose_name": "수술 티켓",
                "verbose_name_plural": "수술 티켓",
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="part_type",
            field=models.CharField(default="upper", max_length=10),
        ),
    ]
