# Generated by Django 5.1.3 on 2025-12-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0005_notice_delete_precaution_delete_stylesetting_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("update_date", models.DateField(verbose_name="업데이트 날짜")),
                ("content", models.CharField(max_length=200, verbose_name="수정 내용")),
            ],
        ),
    ]
